# Generated by Django 5.2.1 on 2026-01-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('eod', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eodexception',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eod_exceptions', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='eodexception',
            name='related_refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eod_exceptions', to='payments.refund'),
        ),
        migrations.AddField(
            model_name='eodexception',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodexception',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.branch'),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='cash_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cash_eods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='digital_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_digital_eods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='discrepancy_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_eod_discrepancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='front_desk_counter',
            field=models.ForeignKey(blank=True, help_text='Front desk counter used for the day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eod_locks', to='clinics.counter'),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='invoices_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_invoices_eods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_eods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_eods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_eods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_eods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodlock',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eodexception',
            name='eod_lock',
            field=models.ForeignKey(help_text='EOD during which this exception was found', on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='eod.eodlock'),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='eod_lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='eod.eodlock'),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='eod_lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_reconciliations', to='eod.eodlock'),
        ),
        migrations.AddIndex(
            model_name='eodlock',
            index=models.Index(fields=['lock_number'], name='eod_eodlock_lock_nu_bcbe92_idx'),
        ),
        migrations.AddIndex(
            model_name='eodlock',
            index=models.Index(fields=['lock_date', 'branch', 'status'], name='eod_eodlock_lock_da_fc7847_idx'),
        ),
        migrations.AddIndex(
            model_name='eodlock',
            index=models.Index(fields=['status', 'has_discrepancies'], name='eod_eodlock_status_5af8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='eodlock',
            index=models.Index(fields=['branch', 'locked_at'], name='eod_eodlock_branch__2d09ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eodlock',
            unique_together={('lock_date', 'branch')},
        ),
        migrations.AddIndex(
            model_name='eodexception',
            index=models.Index(fields=['exception_number'], name='eod_eodexce_excepti_b4e54f_idx'),
        ),
        migrations.AddIndex(
            model_name='eodexception',
            index=models.Index(fields=['exception_date', 'exception_type'], name='eod_eodexce_excepti_2497f1_idx'),
        ),
        migrations.AddIndex(
            model_name='eodexception',
            index=models.Index(fields=['status', 'severity'], name='eod_eodexce_status_48d1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='eodexception',
            index=models.Index(fields=['assigned_to', 'status'], name='eod_eodexce_assigne_cef638_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['summary_number'], name='eod_dailysu_summary_a0a94a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['summary_date', 'summary_type'], name='eod_dailysu_summary_76e3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['branch', 'period_end'], name='eod_dailysu_branch__94089f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashreconciliation',
            index=models.Index(fields=['reconciliation_number'], name='eod_cashrec_reconci_7178be_idx'),
        ),
        migrations.AddIndex(
            model_name='cashreconciliation',
            index=models.Index(fields=['reconciliation_date', 'reconciliation_type'], name='eod_cashrec_reconci_2583c1_idx'),
        ),
        migrations.AddIndex(
            model_name='cashreconciliation',
            index=models.Index(fields=['cashier', 'verified'], name='eod_cashrec_cashier_53aa2c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashreconciliation',
            index=models.Index(fields=['counter', 'reconciliation_date'], name='eod_cashrec_counter_e9e29a_idx'),
        ),
    ]
