# Generated by Django 5.2.1 on 2026-01-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
