# Generated by Django 6.0.1 on 2026-01-18 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_role_config'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBranchRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='accounts_us_user_id_2517ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='accounts_us_role_id_327ba4_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_branch',
        ),
        migrations.AlterField(
            model_name='userbranch',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='clinics.branch'),
        ),
        migrations.AlterField(
            model_name='userbranch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbranchrole',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbranchrole',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='clinics.branch'),
        ),
        migrations.AddField(
            model_name='userbranchrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_roles', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='userbranchrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddIndex(
            model_name='userbranchrole',
            index=models.Index(fields=['user', 'branch', 'is_active'], name='accounts_us_user_id_cb9135_idx'),
        ),
        migrations.AddIndex(
            model_name='userbranchrole',
            index=models.Index(fields=['branch', 'role', 'is_active'], name='accounts_us_branch__dac5a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbranchrole',
            unique_together={('user', 'branch', 'role')},
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
