# Generated by Django 6.0.1 on 2026-01-22 06:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clinics', '0003_counter_created_at_counter_created_by_and_more'),
        ('doctors', '0002_alter_doctor_options_alter_doctorleave_options_and_more'),
        ('patients', '0001_initial'),
        ('visits', '0002_queue_visitdocument_visitvitalsign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date', '-created_at'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['invoice', 'id'], 'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='insurance_claim_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='insurance_claim_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid by Insurance')], default='NOT_APPLICABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes not shown to patient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate Payment'), ('7_DAYS', '7 Days'), ('15_DAYS', '15 Days'), ('30_DAYS', '30 Days'), ('60_DAYS', '60 Days'), ('CUSTOM', 'Custom')], default='IMMEDIATE', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='referral_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_invoices', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN/SAC code for GST', max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_invoice', to='visits.visit'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('TREATMENT', 'Treatment'), ('MEDICINE', 'Medicine'), ('CONSULTATION', 'Consultation'), ('LAB', 'Lab Test'), ('PROCEDURE', 'Procedure'), ('EQUIPMENT', 'Equipment Usage'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['insurance_claim_status'], name='invoices_insuran_b60c72_idx'),
        ),
    ]
