# Generated by Django 5.2.1 on 2026-01-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('medicine_type', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('strength', models.CharField(blank=True, help_text='e.g., 500mg, 10mg/ml', max_length=100)),
                ('unit', models.CharField(blank=True, help_text='e.g., mg, ml, g', max_length=50)),
                ('schedule', models.CharField(blank=True, help_text='H1, H, G, etc.', max_length=10)),
                ('is_controlled', models.BooleanField(default=False)),
                ('default_pack_size', models.CharField(blank=True, max_length=50)),
                ('default_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='medicines_name_017048_idx'), models.Index(fields=['generic_name'], name='medicines_generic_850df6_idx'), models.Index(fields=['medicine_type', 'is_active'], name='medicines_medicin_e3d21f_idx'), models.Index(fields=['is_controlled'], name='medicines_is_cont_c21d95_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('prescription_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('DISPENSED', 'Dispensed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('prescription_type', models.CharField(choices=[('NEW', 'New Prescription'), ('REFILL', 'Refill'), ('RENEWAL', 'Renewal')], default='NEW', max_length=20)),
                ('diagnosis', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('clinical_findings', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('pharmacy_notes', models.TextField(blank=True)),
                ('is_pharmacy_copy_sent', models.BooleanField(default=False)),
                ('pharmacy_sent_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_signature', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='prescriptions/%Y/%m/%d/')),
                ('pdf_hash', models.CharField(blank=True, help_text='SHA-256 hash for verification', max_length=64)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='prescription_qr/')),
                ('verification_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='visits.visit')),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage', models.CharField(help_text='e.g., 1 tablet, 5ml', max_length=100)),
                ('frequency', models.CharField(choices=[('OD', 'Once daily'), ('BD', 'Twice daily'), ('TDS', 'Thrice daily'), ('QID', 'Four times daily'), ('HS', 'At bedtime'), ('SOS', 'As needed'), ('STAT', 'Immediately once'), ('PRN', 'When required')], max_length=10)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('TOPICAL', 'Topical'), ('INHALATION', 'Inhalation'), ('INJECTION', 'Injection'), ('RECTAL', 'Rectal'), ('SUBLINGUAL', 'Sublingual'), ('OTHER', 'Other')], default='ORAL', max_length=20)),
                ('duration_value', models.PositiveIntegerField(default=7)),
                ('duration_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months'), ('UNTIL_FINISHED', 'Until finished')], default='DAYS', max_length=20)),
                ('before_food', models.BooleanField(default=False, help_text='Take before food')),
                ('after_food', models.BooleanField(default=True, help_text='Take after food')),
                ('specific_timing', models.CharField(blank=True, help_text='e.g., Morning, Evening', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Total quantity to dispense', max_digits=10)),
                ('unit', models.CharField(blank=True, help_text='e.g., tablets, ml, bottles', max_length=20)),
                ('allow_generic', models.BooleanField(default=True, help_text='Allow generic substitution')),
                ('allow_brand', models.BooleanField(default=True, help_text='Allow brand substitution')),
                ('instructions', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('is_repeat', models.BooleanField(default=False)),
                ('repeat_count', models.PositiveIntegerField(default=0, help_text='Number of repeats allowed')),
                ('repeat_interval', models.PositiveIntegerField(default=0, help_text='Days between repeats')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='prescriptions.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescriptions.prescription')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescription_medicines',
                'ordering': ['prescription', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispense_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('dispensed_date', models.DateField(auto_now_add=True)),
                ('dispensed_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('pharmacy_name', models.CharField(blank=True, max_length=200)),
                ('pharmacist_name', models.CharField(blank=True, max_length=100)),
                ('pharmacy_license', models.CharField(blank=True, max_length=100)),
                ('verification_method', models.CharField(blank=True, help_text='QR scan, Manual, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_dispenses', to=settings.AUTH_USER_MODEL)),
                ('prescription_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='prescriptions.prescriptionmedicine')),
            ],
            options={
                'db_table': 'prescription_dispenses',
                'ordering': ['-dispensed_date'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_id'], name='prescriptio_prescri_aa4c67_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='prescriptio_patient_e097dd_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'status'], name='prescriptio_doctor__104814_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['visit'], name='prescriptio_visit_i_edfe6f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', 'next_review_date'], name='prescriptio_status_162c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['verification_code'], name='prescriptio_verific_5c8dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionmedicine',
            index=models.Index(fields=['prescription', 'medicine'], name='prescriptio_prescri_706b03_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiondispense',
            index=models.Index(fields=['prescription_medicine', 'dispensed_date'], name='prescriptio_prescri_ac0aba_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiondispense',
            index=models.Index(fields=['dispense_id'], name='prescriptio_dispens_c1620f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiondispense',
            index=models.Index(fields=['pharmacy_name'], name='prescriptio_pharmac_0e5041_idx'),
        ),
    ]
