# Generated by Django 6.0.1 on 2026-01-21 08:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_counter_created_at_counter_created_by_and_more'),
        ('doctors', '0002_alter_doctor_options_alter_doctorleave_options_and_more'),
        ('patients', '0001_initial'),
        ('prescriptions', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('ANTIBIOTIC', 'Antibiotic'), ('ANALGESIC', 'Analgesic (Pain Killer)'), ('ANTI_INFLAMMATORY', 'Anti-inflammatory'), ('ANTISEPTIC', 'Antiseptic'), ('ANESTHETIC', 'Anesthetic'), ('FILLING', 'Filling Material'), ('IMPLANT', 'Implant'), ('ORTHODONTIC', 'Orthodontic'), ('PROSTHETIC', 'Prosthetic'), ('HYGIENE', 'Oral Hygiene'), ('OTHER', 'Other')], max_length=50)),
                ('form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('OINTMENT', 'Ointment'), ('CREAM', 'Cream'), ('GEL', 'Gel'), ('MOUTHWASH', 'Mouthwash'), ('PASTE', 'Paste'), ('POWDER', 'Powder'), ('SPRAY', 'Spray'), ('DROPS', 'Drops'), ('LOZENGE', 'Lozenge'), ('OTHER', 'Other')], max_length=50)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='Unit', max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('max_stock_level', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('indications', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('storage_instructions', models.TextField(blank=True)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('schedule', models.CharField(blank=True, max_length=10)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'medications',
                'ordering': ['name', 'brand'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 1 tablet', max_length=100)),
                ('frequency', models.CharField(choices=[('OD', 'Once daily'), ('BD', 'Twice daily'), ('TDS', 'Three times daily'), ('QID', 'Four times daily'), ('QHS', 'At bedtime'), ('PRN', 'As needed'), ('STAT', 'Immediately'), ('Q4H', 'Every 4 hours'), ('Q6H', 'Every 6 hours'), ('Q8H', 'Every 8 hours'), ('Q12H', 'Every 12 hours'), ('QW', 'Once a week'), ('BIW', 'Twice a week'), ('TIW', 'Three times a week')], default='BD', max_length=20)),
                ('duration', models.PositiveIntegerField(default=7, help_text='Duration value')),
                ('duration_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('instructions', models.TextField(blank=True, help_text='Specific instructions for this medication')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('dispensed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
                'db_table': 'prescription_items',
                'ordering': ['prescription', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('template_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('specialization', models.CharField(choices=[('GENERAL', 'General Dentistry'), ('ORTHO', 'Orthodontics'), ('PERIO', 'Periodontics'), ('ENDO', 'Endodontics'), ('PEDO', 'Pediatric Dentistry'), ('SURG', 'Oral Surgery'), ('PROS', 'Prosthodontics'), ('ALL', 'All Specializations')], default='GENERAL', max_length=50)),
                ('diagnoses', models.TextField(blank=True, help_text='Common diagnoses (comma-separated)')),
                ('default_diagnosis', models.TextField(blank=True)),
                ('default_notes', models.TextField(blank=True)),
                ('default_instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Prescription Template',
                'verbose_name_plural': 'Prescription Templates',
                'db_table': 'prescription_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_dosage', models.CharField(default='As directed', max_length=100)),
                ('default_frequency', models.CharField(choices=[('OD', 'Once daily'), ('BD', 'Twice daily'), ('TDS', 'Three times daily'), ('QID', 'Four times daily'), ('QHS', 'At bedtime'), ('PRN', 'As needed'), ('STAT', 'Immediately'), ('Q4H', 'Every 4 hours'), ('Q6H', 'Every 6 hours'), ('Q8H', 'Every 8 hours'), ('Q12H', 'Every 12 hours'), ('QW', 'Once a week'), ('BIW', 'Twice a week'), ('TIW', 'Three times a week')], default='BD', max_length=20)),
                ('default_duration', models.PositiveIntegerField(default=7)),
                ('default_duration_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=10)),
                ('default_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('default_instructions', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Medication',
                'verbose_name_plural': 'Template Medications',
                'db_table': 'template_medications',
                'ordering': ['template', 'display_order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicines_name_017048_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicines_generic_850df6_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicines_medicin_e3d21f_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='medicines_is_cont_c21d95_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescriptiondispense',
            name='prescriptio_prescri_ac0aba_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescriptiondispense',
            name='prescriptio_dispens_c1620f_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescriptiondispense',
            name='prescriptio_pharmac_0e5041_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescriptionmedicine',
            name='prescriptio_prescri_706b03_idx',
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-issue_date', '-created_at'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_patient_e097dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_doctor__104814_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_visit_i_edfe6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_status_162c4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_verific_5c8dcd_idx',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='pharmacy_sent_at',
            new_name='dispensed_at',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='is_pharmacy_copy_sent',
            new_name='is_refillable',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='next_review_date',
            new_name='last_refill_date',
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensing_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='clinics.branch'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, help_text='General instructions for patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='insurance_covered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='max_refills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, help_text="Doctor's notes"),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='valid_until',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Clinical diagnosis'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='visits.visit'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'doctor', 'issue_date'], name='prescriptio_patient_1de8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', 'valid_until'], name='prescriptio_status_68f835_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'issue_date'], name='prescriptio_doctor__d64cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['is_refillable', 'refills_remaining'], name='prescriptio_is_refi_34c96e_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['medicine_id'], name='medications_medicin_2f250a_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['name', 'generic_name'], name='medications_name_f39e65_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['category'], name='medications_categor_c1b594_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['requires_prescription', 'is_active'], name='medications_require_a6cd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['in_stock', 'current_stock'], name='medications_in_stoc_8f4513_idx'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='prescriptions.medication'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatemedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_medications', to='prescriptions.medication'),
        ),
        migrations.AddField(
            model_name='templatemedication',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='prescriptions.prescriptiontemplate'),
        ),
        migrations.RemoveField(
            model_name='prescriptiondispense',
            name='prescription_medicine',
        ),
        migrations.RemoveField(
            model_name='prescriptiondispense',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='advice',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='clinical_findings',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_signature',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='follow_up_instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pdf_hash',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pharmacy_notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='verification_code',
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['prescription', 'medication'], name='prescriptio_prescri_9f916f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['is_dispensed'], name='prescriptio_is_disp_2d8ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplate',
            index=models.Index(fields=['template_id'], name='prescriptio_templat_44f89e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplate',
            index=models.Index(fields=['specialization', 'is_active'], name='prescriptio_special_71689c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatemedication',
            unique_together={('template', 'medication')},
        ),
        migrations.DeleteModel(
            name='PrescriptionDispense',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='PrescriptionMedicine',
        ),
    ]
