# Generated by Django 6.0.1 on 2026-01-22 11:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_options_alter_invoiceitem_options_and_more'),
        ('clinics', '0003_counter_created_at_counter_created_by_and_more'),
        ('patients', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Split',
                'verbose_name_plural': 'Payment Splits',
                'db_table': 'payment_splits',
            },
        ),
        migrations.AlterUniqueTogether(
            name='paymentreconciliation',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='paymentreconciliation',
            name='payments_pa_reconci_7067e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentreconciliation',
            name='payments_pa_reconci_95c8bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentreconciliation',
            name='payments_pa_status_4a26d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_status_70813e_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='locked_eod_id',
            new_name='account_number',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_payment_c27a96_idx',
            old_name='payments_pa_payment_a0847d_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_invoice_58a325_idx',
            old_name='payments_pa_invoice_e2429a_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_patient_3ac440_idx',
            old_name='payments_pa_patient_617260_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_payment_e40d18_idx',
            old_name='payments_pa_payment_34513f_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreceipt',
            new_name='payment_rec_receipt_5b8ffe_idx',
            old_name='payments_pa_receipt_fee67b_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreceipt',
            new_name='payment_rec_payment_41e9d8_idx',
            old_name='payments_pa_payment_efbe81_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='refunds_refund__a55d04_idx',
            old_name='payments_re_refund__3efd22_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='refunds_payment_908281_idx',
            old_name='payments_re_payment_4444a0_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='refunds_status_946d41_idx',
            old_name='payments_re_status_0cd2b9_idx',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='eod_locked',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_authorization_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='counter',
            field=models.ForeignKey(blank=True, help_text='Counter where payment was received', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='clinics.counter'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='insurance_approval_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes not shown to patient'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked by EOD process'),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='icon_class',
            field=models.CharField(blank=True, help_text='CSS icon class for UI display', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF receipt', null=True, upload_to='receipts/pdf/'),
        ),
        migrations.AddField(
            model_name='refund',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked by EOD process'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clinics.branch'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Whether this method requires manager approval'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='clinics.branch'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='generated_html',
            field=models.TextField(blank=True, help_text='Generated HTML receipt'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='html_template',
            field=models.TextField(blank=True, help_text='HTML template used for this receipt'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_link', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='clinics.branch'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_method',
            field=models.CharField(choices=[('CASH', 'Cash Refund'), ('CARD_REVERSAL', 'Card Reversal'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT_NOTE', 'Credit Note'), ('ADJUSTMENT', 'Adjustment to Account')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'is_locked'], name='payments_status_709898_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_number'], name='payments_referen_a186d6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='payments_receipt_6cb761_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['security_code'], name='payment_rec_securit_1537d5_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['reference_number'], name='refunds_referen_76e208_idx'),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='payment_methods',
        ),
        migrations.AlterModelTable(
            name='paymentreceipt',
            table='payment_receipts',
        ),
        migrations.AlterModelTable(
            name='refund',
            table='refunds',
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentsplit',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='payments.paymentmethod'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='eod_locked',
        ),
        migrations.DeleteModel(
            name='PaymentReconciliation',
        ),
    ]
