# Generated by Django 5.2.1 on 2026-01-17 13:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Treatment Categories',
                'db_table': 'treatment_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doctor_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Percentage of base price that goes to doctor', max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Tax percentage applied', max_digits=5)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('COMPLEX', 'Complex'), ('SPECIALIST', 'Specialist')], default='MEDIUM', max_length=20)),
                ('duration_value', models.PositiveIntegerField(default=30)),
                ('duration_unit', models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days')], default='MINUTES', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('procedure_steps', models.TextField(blank=True, help_text='Step-by-step procedure')),
                ('materials_required', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_lab', models.BooleanField(default=False)),
                ('lab_days', models.PositiveIntegerField(default=0, help_text='Lab processing time in days')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='treatments.treatmentcategory')),
            ],
            options={
                'db_table': 'treatments',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('plan_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSED', 'Proposed to Patient'), ('ACCEPTED', 'Accepted by Patient'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_start_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_goals', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatment_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DEFERRED', 'Deferred')], default='PENDING', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('tooth_number', models.CharField(blank=True, help_text='Tooth FDI notation', max_length=20)),
                ('surface', models.CharField(blank=True, help_text='Tooth surface', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('scheduled_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plan_items', to='visits.visit')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='treatments.treatment')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='treatments.treatmentplan')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatment_plan_items',
                'ordering': ['treatment_plan', 'visit_number'],
            },
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['category', 'is_active'], name='treatments_categor_3d8315_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['code'], name='treatments_code_08218d_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['base_price'], name='treatments_base_pr_6a8999_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['patient', 'status'], name='treatment_p_patient_5778c2_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['doctor', 'status'], name='treatment_p_doctor__86354b_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['plan_id'], name='treatment_p_plan_id_a10d13_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['status', 'estimated_start_date'], name='treatment_p_status_20d5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplanitem',
            index=models.Index(fields=['treatment_plan', 'status'], name='treatment_p_treatme_ab27ad_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplanitem',
            index=models.Index(fields=['status', 'scheduled_date'], name='treatment_p_status_e46f66_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplanitem',
            index=models.Index(fields=['scheduled_visit'], name='treatment_p_schedul_73f6e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='treatmentplanitem',
            unique_together={('treatment_plan', 'visit_number')},
        ),
    ]
