# Generated by Django 5.2.1 on 2026-01-22 04:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_counter_created_at_counter_created_by_and_more'),
        ('doctors', '0002_alter_doctor_options_alter_doctorleave_options_and_more'),
        ('patients', '0001_initial'),
        ('treatments', '0001_initial'),
        ('visits', '0002_queue_visitdocument_visitvitalsign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('visit_number', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'template_treatments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ToothChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32')], max_length=3)),
                ('quadrant', models.IntegerField(choices=[(1, 'Upper Right'), (2, 'Upper Left'), (3, 'Lower Left'), (4, 'Lower Right')])),
                ('fdi_notation', models.CharField(max_length=5, unique=True)),
                ('universal_notation', models.CharField(max_length=5)),
                ('name', models.CharField(help_text='Tooth name (e.g., Maxillary Right First Molar)', max_length=100)),
                ('type', models.CharField(choices=[('INCISOR', 'Incisor'), ('CANINE', 'Canine'), ('PREMOLAR', 'Premolar'), ('MOLAR', 'Molar'), ('WISDOM', 'Wisdom Tooth')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tooth_charts',
            },
        ),
        migrations.CreateModel(
            name='TreatmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('PRE_OP', 'Pre-operative'), ('INTRA_OP', 'Intra-operative'), ('POST_OP', 'Post-operative'), ('FOLLOW_UP', 'Follow-up'), ('COMPLICATION', 'Complication'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('content', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attached files')),
                ('is_critical', models.BooleanField(default=False, help_text='Critical note requiring attention')),
            ],
            options={
                'db_table': 'treatment_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'treatment_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='treatmentcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Treatment Categories'},
        ),
        migrations.AlterModelOptions(
            name='treatmentplanitem',
            options={'ordering': ['treatment_plan', 'visit_number', 'order']},
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='precautions',
            new_name='post_op_instructions',
        ),
        migrations.RenameField(
            model_name='treatmentplan',
            old_name='notes',
            new_name='clinical_notes',
        ),
        migrations.RenameField(
            model_name='treatmentplanitem',
            old_name='notes',
            new_name='complications',
        ),
        migrations.AddField(
            model_name='treatment',
            name='assistant_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='treatment',
            name='contraindications',
            field=models.TextField(blank=True, help_text='When not to perform this treatment'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='display_in_portal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for patients', max_length=200),
        ),
        migrations.AddField(
            model_name='treatment',
            name='equipment_required',
            field=models.JSONField(blank=True, default=list, help_text='List of equipment needed'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='inventory_items',
            field=models.JSONField(blank=True, default=list, help_text='Inventory items consumed with quantities'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='lab_type',
            field=models.CharField(blank=True, help_text='Type of lab work needed', max_length=50),
        ),
        migrations.AddField(
            model_name='treatment',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='medical_conditions',
            field=models.JSONField(blank=True, default=list, help_text='Medical conditions that affect this treatment'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price (for discounts)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='num_sessions',
            field=models.PositiveIntegerField(default=1, help_text='Number of sessions required'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order in lists'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treatment',
            name='recovery_days',
            field=models.PositiveIntegerField(default=0, help_text='Estimated recovery time'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('95.00'), help_text='Success rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='treatment',
            name='suitable_for_age',
            field=models.CharField(choices=[('CHILD', 'Child (0-12)'), ('TEEN', 'Teenager (13-19)'), ('ADULT', 'Adult (20-59)'), ('SENIOR', 'Senior (60+)'), ('ALL', 'All Ages')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='treatment',
            name='suitable_for_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ALL', 'All')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='treatment',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AddField(
            model_name='treatmentcategory',
            name='color',
            field=models.CharField(blank=True, default='#4CAF50', help_text='Hex color for UI', max_length=20),
        ),
        migrations.AddField(
            model_name='treatmentcategory',
            name='display_in_portal',
            field=models.BooleanField(default=True, help_text='Show in patient portal'),
        ),
        migrations.AddField(
            model_name='treatmentcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class for UI', max_length=50),
        ),
        migrations.AddField(
            model_name='treatmentcategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='SEO keywords'),
        ),
        migrations.AddField(
            model_name='treatmentcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order in UI'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='clinics.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='complexity_score',
            field=models.IntegerField(default=0, help_text='1-10 score of plan complexity'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='consent_form_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='consent_form_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='dental_chart',
            field=models.JSONField(blank=True, default=dict, help_text='JSON representation of dental chart with conditions'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='diagnosis_codes',
            field=models.JSONField(blank=True, default=list, help_text='ICD codes'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='insurance_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='insurance_coverage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='insurance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='treatments.treatmentplan'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='payment_plan',
            field=models.JSONField(blank=True, default=dict, help_text='Payment schedule with dates and amounts'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='post_op_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='pre_op_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='priority',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency'), ('ELECTIVE', 'Elective')], default='ROUTINE', max_length=20),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_plans', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='risks_and_complications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='satisfaction_score',
            field=models.IntegerField(blank=True, help_text='Patient satisfaction 1-10', null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='version',
            field=models.IntegerField(default=1, help_text='Plan version number'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='xray_images',
            field=models.JSONField(blank=True, default=list, help_text='List of X-ray image URLs'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='anesthesia_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='anesthesia_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Item that must be completed before this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencies', to='treatments.treatmentplanitem'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='equipment_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='follow_up_days',
            field=models.IntegerField(default=7, help_text='Days until follow-up'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='materials_used',
            field=models.JSONField(blank=True, default=list, help_text='Materials actually used'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Order within visit'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='patient_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_treatments', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='phase',
            field=models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic'), ('PREVENTIVE', 'Preventive'), ('RESTORATIVE', 'Restorative'), ('SURGICAL', 'Surgical'), ('ORTHODONTIC', 'Orthodontic'), ('PROSTHETIC', 'Prosthetic'), ('MAINTENANCE', 'Maintenance')], default='RESTORATIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='procedure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='quadrant',
            field=models.IntegerField(blank=True, choices=[(1, 'Upper Right'), (2, 'Upper Left'), (3, 'Lower Left'), (4, 'Lower Right')], null=True),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='quality_score',
            field=models.IntegerField(blank=True, help_text='1-10 quality score', null=True),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='tooth_condition',
            field=models.CharField(blank=True, choices=[('CARIES', 'Caries'), ('FRACTURE', 'Fracture'), ('ROOT_CANAL', 'Root Canal Treated'), ('MISSING', 'Missing'), ('IMPACTED', 'Impacted'), ('DISCOLORED', 'Discolored'), ('SENSITIVE', 'Sensitive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='difficulty',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('SPECIALIST', 'Specialist'), ('SURGICAL', 'Surgical')], default='INTERMEDIATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='doctor_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Doctor commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='duration_unit',
            field=models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days'), ('SESSIONS', 'Sessions')], default='MINUTES', max_length=10),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='duration_value',
            field=models.PositiveIntegerField(default=30, help_text='Duration value'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='lab_days',
            field=models.PositiveIntegerField(default=0, help_text='Lab processing time'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='materials_required',
            field=models.JSONField(blank=True, default=list, help_text='List of materials with quantities'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='procedure_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSED', 'Proposed to Patient'), ('REVISED', 'Revised'), ('ACCEPTED', 'Accepted by Patient'), ('CONTRACT_SIGNED', 'Contract Signed'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFERRED', 'Referred to Specialist')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='treatmentplanitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DEFERRED', 'Deferred'), ('POSTPONED', 'Postponed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='treatmentplanitem',
            name='surface',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='treatmentplanitem',
            name='tooth_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['popularity_score'], name='treatments_popular_8271b7_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['branch', 'created_at'], name='treatment_p_branch__d42e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplanitem',
            index=models.Index(fields=['tooth_number'], name='treatment_p_tooth_n_4149ce_idx'),
        ),
        migrations.AddField(
            model_name='templatetreatment',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatments.treatment'),
        ),
        migrations.AddField(
            model_name='treatmentnote',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmentnote',
            name='treatment_plan_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='treatments.treatmentplanitem'),
        ),
        migrations.AddField(
            model_name='treatmentnote',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmenttemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='treatments.treatmentcategory'),
        ),
        migrations.AddField(
            model_name='treatmenttemplate',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmenttemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmenttemplate',
            name='treatments',
            field=models.ManyToManyField(related_name='templates', through='treatments.TemplateTreatment', to='treatments.treatment'),
        ),
        migrations.AddField(
            model_name='treatmenttemplate',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatetreatment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatments.treatmenttemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='templatetreatment',
            unique_together={('template', 'treatment')},
        ),
    ]
