# Generated by Django 6.0.1 on 2026-01-19 14:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
        ('clinics', '0002_branch_eod_locked_at_branch_eod_locked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['id'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='record_hash',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['record_hash'], name='audit_audit_record__f009ac_idx'),
        ),
    ]
