# Generated by Django 6.0.1 on 2026-01-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_options_auditlog_previous_hash_and_more'),
        ('clinics', '0003_counter_created_at_counter_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinics.branch', verbose_name='Branch'),
        ),
    ]
