# Generated by Django 6.0.1 on 2026-01-21 08:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_counter_created_at_counter_created_by_and_more'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['doctor_id'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='doctorleave',
            options={'ordering': ['-start_date'], 'verbose_name': 'Doctor Leave', 'verbose_name_plural': 'Doctor Leaves'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['doctor', 'day_of_week'], 'verbose_name': 'Doctor Schedule', 'verbose_name_plural': 'Doctor Schedules'},
        ),
        migrations.RemoveIndex(
            model_name='doctorleave',
            name='doctor_leav_doctor__396dd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctorschedule',
            name='doctor_sche_doctor__1904cc_idx',
        ),
        migrations.RenameField(
            model_name='doctorleave',
            old_name='leave_date',
            new_name='end_date',
        ),
        migrations.AlterUniqueTogether(
            name='doctorleave',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctor',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='follow_up_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_accepting_new_patients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages_spoken',
            field=models.CharField(blank=True, default='English', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_issuing_authority',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='npi_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='preferred_contact_method',
            field=models.CharField(choices=[('CLINIC', 'Clinic Phone'), ('PERSONAL', 'Personal Phone'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='CLINIC', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='secondary_branches',
            field=models.ManyToManyField(blank=True, related_name='secondary_doctors', to='clinics.branch'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_signatures/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(blank=True, default='Dr.', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='covering_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_leaves', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='leave_type',
            field=models.CharField(choices=[('VACATION', 'Vacation'), ('SICK', 'Sick Leave'), ('PERSONAL', 'Personal Leave'), ('EMERGENCY', 'Emergency'), ('TRAINING', 'Training/Conference'), ('OTHER', 'Other')], default='VACATION', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='branch',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='clinics.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='chair_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='primary_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_doctors', to='clinics.branch'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('GENERAL', 'General Dentistry'), ('ORTHO', 'Orthodontics'), ('PERIO', 'Periodontics'), ('ENDO', 'Endodontics'), ('PEDO', 'Pediatric Dentistry'), ('SURG', 'Oral Surgery'), ('PROS', 'Prosthodontics'), ('RADIO', 'Oral Radiology'), ('PATHO', 'Oral Pathology'), ('PUBLIC', 'Public Health Dentistry')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='max_patients_per_slot',
            field=models.PositiveIntegerField(default=1, help_text='Maximum patients per time slot'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='slot_duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'branch', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_accepting_new_patients'], name='doctors_is_acce_c59078_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorleave',
            index=models.Index(fields=['doctor', 'start_date', 'end_date'], name='doctor_leav_doctor__5fcdb1_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorleave',
            index=models.Index(fields=['doctor', 'status'], name='doctor_leav_doctor__69983f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorleave',
            index=models.Index(fields=['start_date', 'end_date'], name='doctor_leav_start_d_4e7309_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['doctor', 'branch', 'day_of_week', 'is_active'], name='doctor_sche_doctor__c5963c_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['branch', 'day_of_week', 'is_active'], name='doctor_sche_branch__a01f54_idx'),
        ),
    ]
