# Generated by Django 5.2.1 on 2026-01-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('in_consultation', 'In Consultation'), ('ready_for_billing', 'Ready for Billing'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registered', max_length=50)),
                ('appointment_source', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('ONLINE', 'Online Booking'), ('PHONE', 'Phone Call'), ('REFERRAL', 'Doctor Referral'), ('FOLLOW_UP', 'Follow-up')], default='WALK_IN', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('actual_checkin', models.DateTimeField(blank=True, null=True)),
                ('actual_checkout', models.DateTimeField(blank=True, null=True)),
                ('wait_duration', models.DurationField(blank=True, help_text='Waiting time before consultation', null=True)),
                ('consultation_duration', models.DurationField(blank=True, help_text='Actual consultation time', null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='clinics.branch')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='doctors.doctor')),
                ('follow_up_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='visits.visit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visits',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in minutes')),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.branch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='visits.visit')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['appointment_date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_id'], name='visits_visit_i_55c4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', 'status'], name='visits_patient_6652a2_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['doctor', 'status', 'scheduled_date'], name='visits_doctor__d9ad1d_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['branch', 'status', 'scheduled_date'], name='visits_branch__d73452_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', 'scheduled_date'], name='visits_status_1753bf_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_id'], name='appointment_appoint_4da827_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_date'], name='appointment_patient_ee8848_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date', 'status'], name='appointment_doctor__889281_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['branch', 'appointment_date'], name='appointment_branch__e491c9_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='appointment_status_06f84b_idx'),
        ),
    ]
