# Generated by Django 6.0.1 on 2026-01-21 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_counter_created_at_counter_created_by_and_more'),
        ('doctors', '0002_alter_doctor_options_alter_doctorleave_options_and_more'),
        ('patients', '0001_initial'),
        ('treatments', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.IntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('SKIPPED', 'Skipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_minutes', models.IntegerField(default=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'queues',
                'ordering': ['queue_number'],
            },
        ),
        migrations.CreateModel(
            name='VisitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PRESCRIPTION', 'Prescription'), ('REPORT', 'Medical Report'), ('XRAY', 'X-Ray Image'), ('SCAN', 'Scan Result'), ('PHOTO', 'Clinical Photo'), ('CONSENT', 'Consent Form'), ('REFERRAL', 'Referral Letter'), ('CERTIFICATE', 'Medical Certificate'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='visit_documents/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='visit_thumbnails/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'visit_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitVitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'visit_vital_signs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='expected_procedures',
            field=models.JSONField(blank=True, default=list, help_text='List of expected procedures'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_waiting_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_appointments', to='visits.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_times',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred alternative times'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_pattern',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('TREATMENT', 'Treatment'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency'), ('SURGERY', 'Surgery'), ('CHECKUP', 'Regular Checkup')], default='CONSULTATION', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='assigned_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clinics.counter'),
        ),
        migrations.AddField(
            model_name='visit',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='dental_issues',
            field=models.JSONField(blank=True, default=dict, help_text='JSON of affected teeth/areas'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='estimated_wait_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='follow_up_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='insurance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='insurance_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='queue_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='referral_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='visit',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='treatments.treatmentplan'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('TREATMENT', 'Treatment'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency'), ('SURGERY', 'Surgery'), ('CHECKUP', 'Regular Checkup')], default='CONSULTATION', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='appointment_source',
            field=models.CharField(choices=[('WALK_IN', 'Walk-in'), ('ONLINE', 'Online Booking'), ('PHONE', 'Phone Call'), ('REFERRAL', 'Doctor Referral'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency')], default='WALK_IN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_waiting_list', 'appointment_date'], name='appointment_is_wait_ec37d8_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['queue_number', 'branch'], name='visits_queue_n_2d5c82_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['priority', 'scheduled_date'], name='visits_priorit_95205f_idx'),
        ),
        migrations.AddField(
            model_name='queue',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='clinics.branch'),
        ),
        migrations.AddField(
            model_name='queue',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='clinics.counter'),
        ),
        migrations.AddField(
            model_name='queue',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='queue',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='visitdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitdocument',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='visitvitalsign',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitvitalsign',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='visits.visit'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['branch', 'status', 'queue_number'], name='queues_branch__bcd900_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['doctor', 'status'], name='queues_doctor__be5732_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['visit'], name='queues_visit_i_716e28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('branch', 'queue_number')},
        ),
    ]
